services:
  psql:
    container_name: psql
    image: postgres:17.7-alpine3.22
    restart: always
    networks:
      - mainnet
    volumes:
      - db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

networks:
  mainnet:
    driver: bridge

volumes:
  db:
